### ISSUE TITLE
device services should be restarted on mac reboot automatically

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#152]
It seems like we implemented auto recovery on mac reboot via this improvement:
https://github.com/zebrunner/mcloud-ios/issues/151 

@dhreben, let's test how it works with real device and simulator on our stage server

**Comment by dhreben** [comment]
Reopened


Simulator is not available on STF with unhealthy status after reboot Mac. As well simulator is not started automatically on Xcode.


**Log simulator:** 

```
dmclouds-Mac-mini:mcloud-ios idmcloud$  tail -n 100 -f ./logs/iPhone_14_Pro.log
2022-12-30 13:58:53:418 - [HTTP] --> HEAD /wd/hub/status-wda
2022-12-30 13:58:53:418 - [HTTP] {}
2022-12-30 13:58:53:418 - [debug] [GENERIC] Calling AppiumDriver.getStatusWDA() with args: []
2022-12-30 13:58:53:421 - [BaseDriver] Cannot send GET request to 'http://localhost:20071/status'. Original error: connect ECONNREFUSED ::1:20071
2022-12-30 13:58:53:422 - [debug] [GENERIC] Encountered internal error running command: Error for sending of WDA status http call. See appium logs for details[[[--udid E791..............ECFB989 --name iPhone_14_Pro --sessionId undefined]]]
2022-12-30 13:58:53:422 - [debug] [GENERIC] Error: Error for sending of WDA status http call. See appium logs for details
2022-12-30 13:58:53:422 - [debug] [GENERIC]     at AppiumDriver.getStatusWDA (/Users/idmcloud/.nvm/versions/node/v17.1.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:189:13)
2022-12-30 13:58:53:422 - [debug] [GENERIC]     at runMicrotasks (<anonymous>)
2022-12-30 13:58:53:422 - [debug] [GENERIC]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-30 13:58:53:423 - [HTTP] <-- HEAD /wd/hub/status-wda 500 5 ms - 914
2022-12-30 13:58:53:423 - [HTTP] 
2022-12-30 13:58:54:426 - [HTTP] --> HEAD /wd/hub/status-wda
2022-12-30 13:58:54:426 - [HTTP] {}
2022-12-30 13:58:54:426 - [debug] [GENERIC] Calling AppiumDriver.getStatusWDA() with args: []
2022-12-30 13:58:54:428 - [BaseDriver] Cannot send GET request to 'http://localhost:20071/status'. Original error: connect ECONNREFUSED ::1:20071
2022-12-30 13:58:54:428 - [debug] [GENERIC] Encountered internal error running command: Error for sending of WDA status http call. See appium logs for details[[[--udid E791..............ECFB989 --name iPhone_14_Pro --sessionId undefined]]]
2022-12-30 13:58:54:428 - [debug] [GENERIC] Error: Error for sending of WDA status http call. See appium logs for details
2022-12-30 13:58:54:428 - [debug] [GENERIC]     at AppiumDriver.getStatusWDA (/Users/idmcloud/.nvm/versions/node/v17.1.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:189:13)
2022-12-30 13:58:54:428 - [debug] [GENERIC]     at runMicrotasks (<anonymous>)
2022-12-30 13:58:54:428 - [debug] [GENERIC]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by vdelendik** [comment]
done loading dedicated `LaunchAgents/ZebrunnerDevicesManager.plist` during setup.
it should launch and keep up&running `./zebrunner.sh listen`
Hopefully due to the KeepAlive and RunAtLoad it might be started after reboot. The only question right now if rule is loaded first or `ios listen` got new attached actions...

**Comment by dhreben** [comment]
Still repro.
After reboot mac ios and simulators are not up and running.
Will be checked after the implementation of this ticket https://github.com/zebrunner/mcloud-ios/issues/181

**Comment by vdelendik** [comment]
closing as dupe of #181
